import { useEffect, useState } from "react";
import { FlatList, Linking, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { apiRequest } from "../src/api/client";
import { Button, Chip } from "../src/components/CommunityUI";
import { EmptyState } from "../src/components/EmptyState";
import { ListItem, ScreenHeader, SkeletonList } from "../src/components/SocialUI";
import { useAuthStore } from "../src/store/authStore";
import { colors } from "../src/theme/colors";
import { fonts } from "../src/theme/fonts";

type Mode = "submissions" | "reports" | "audit";
const PATHS: Record<Mode, string> = { submissions: "/community/moderation/submissions", reports: "/community/moderation/reports", audit: "/community/moderation/audit" };
export default function ModeratorScreen() {
  const user = useAuthStore(state => state.user); const [mode, setMode] = useState<Mode>("submissions"); const [items, setItems] = useState<any[]>([]); const [reason, setReason] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); try { setItems(await apiRequest<any[]>(PATHS[mode], { auth: true })); setError(""); } catch (e: any) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [mode]);
  async function decide(item: any, decision: "approve" | "reject") { try { const path = mode === "reports" ? `/community/moderation/reports/${item.id}` : `/community/moderation/submissions/${item.id}`; await apiRequest(path, { method: "POST", auth: true, body: { decision, reason } }); setReason(""); await load(); } catch (e: any) { setError(e.message); } }
  if (!user || !["ADMIN", "MODERATOR"].includes(user.role)) return <SafeAreaView style={styles.safe}><ScreenHeader title="Moderator tools" /><EmptyState title="Restricted area" subtitle="Moderator permission is required." /></SafeAreaView>;
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><ScreenHeader title="Moderator tools" /><View style={styles.chips}>{(["submissions", "reports", "audit"] as Mode[]).map(value => <Chip key={value} title={value === "submissions" ? "Queue & appeals" : value[0].toUpperCase() + value.slice(1)} active={mode === value} onPress={() => setMode(value)} />)}</View>{error ? <Text style={styles.error}>{error}</Text> : null}{loading ? <View style={styles.content}><SkeletonList /></View> : <FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={styles.content} ListHeaderComponent={mode !== "audit" && items.length ? <TextInput accessibilityLabel="Decision reason" placeholder="Reason for this moderation decision" placeholderTextColor={colors.textMuted} value={reason} onChangeText={setReason} multiline style={styles.input} /> : null} ListEmptyComponent={<EmptyState title="Nothing needs attention" subtitle="This moderation view is clear." />} renderItem={({ item }) => mode === "audit" ? <ListItem icon="shield-checkmark-outline" title={item.action.replaceAll("_", " ")} subtitle={`${item.target_type} · ${new Date(item.created_at).toLocaleString()}`} /> : <View style={styles.item}><ListItem icon={mode === "reports" ? "flag-outline" : "document-text-outline"} title={mode === "reports" ? `Reported ${item.target_type}` : item.payload?.title || item.payload?.name || item.kind} subtitle={mode === "reports" ? item.reason : `${item.state} · ${(item.risk_flags || []).join(" · ")}`} />{item.payload?.description ? <Text style={styles.detail}>{item.payload.description}</Text> : null}{item.payload?.source_url ? <Text style={styles.link} onPress={() => Linking.openURL(item.payload.source_url)}>Open source</Text> : null}{item.payload?.evidence_url ? <Text style={styles.link} onPress={() => Linking.openURL(item.payload.evidence_url)}>Open evidence</Text> : null}{item.appeal ? <Text style={styles.detail}>Appeal: {item.appeal}</Text> : null}<View style={styles.actions}><View style={styles.action}><Button title="Approve" busy={loading} onPress={() => decide(item, "approve")} /></View><View style={styles.action}><Button title={mode === "reports" ? "Dismiss" : "Reject"} busy={loading} onPress={() => decide(item, "reject")} /></View></View></View>} />}</SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7, paddingHorizontal: 18, paddingBottom: 10 }, content: { paddingHorizontal: 18, paddingBottom: 28, flexGrow: 1 }, error: { color: colors.danger, paddingHorizontal: 18 }, input: { minHeight: 80, borderWidth: 1, borderColor: colors.border, borderRadius: 17, backgroundColor: colors.surface, padding: 12, color: colors.text, textAlignVertical: "top", marginVertical: 10 }, item: { paddingBottom: 18 }, detail: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 11, lineHeight: 16, marginLeft: 56 }, link: { color: colors.primaryDark, fontFamily: fonts.semibold, fontSize: 11, marginLeft: 56, marginTop: 6 }, actions: { flexDirection: "row", gap: 8, marginTop: 10 }, action: { flex: 1 } });
