import { useEffect, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { apiRequest } from "../../src/api/client";
import { getProfile, getProfileHistory, type PublicProfile } from "../../src/api/community";
import { Chip } from "../../src/components/CommunityUI";
import { EmptyState } from "../../src/components/EmptyState";
import { Avatar, IconButton, ListItem, OverflowMenu, ScreenHeader, SkeletonList, Stat } from "../../src/components/SocialUI";
import { useAuthStore } from "../../src/store/authStore";
import { colors } from "../../src/theme/colors";
import { fonts } from "../../src/theme/fonts";

type Tab = "contributions" | "reviews" | "collections";
export default function ProfileScreen() {
  const user = useAuthStore(state => state.user); const token = useAuthStore(state => state.token); const logout = useAuthStore(state => state.logout);
  const [profile, setProfile] = useState<PublicProfile | null>(null); const [tab, setTab] = useState<Tab>("contributions"); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [more, setMore] = useState(false); const [menu, setMenu] = useState(false);
  useEffect(() => { if (!user) return; getProfile(user.id).then(setProfile).catch(e => setError(e.message)); }, [user?.id]);
  async function load(append = false) { if (!user) return; setLoading(true); try { let result: any[]; if (tab === "collections") result = (await apiRequest<any[]>("/community/collections", { auth: true })).filter(item => item.user_id === user.id); else result = await getProfileHistory(user.id, tab, append ? items.length : 0, 12); setItems(current => append ? [...current, ...result] : result); setMore(tab !== "collections" && result.length === 12); setError(""); } catch (e: any) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { setItems([]); void load(false); }, [user?.id, tab]);
  async function signOut() { await logout(); router.replace("/welcome"); }
  if (!token || !user) return <SafeAreaView style={styles.safe} edges={["top"]}><View style={styles.guest}><Ionicons name="people" size={42} color={colors.primary} /><Text style={styles.guestTitle}>Your city, your profile.</Text><Text style={styles.guestText}>Save plans, follow local voices and contribute what makes Bratislava useful.</Text><Pressable style={styles.primary} onPress={() => router.push({ pathname: "/auth", params: { mode: "register" } })}><Text style={styles.primaryText}>Create an account</Text></Pressable><Pressable style={styles.secondary} onPress={() => router.push({ pathname: "/auth", params: { mode: "login" } })}><Text style={styles.secondaryText}>Log in</Text></Pressable></View></SafeAreaView>;
  const visible = profile ?? ({ ...user, contributions_count: 0, reviews_count: 0, followers: 0, following: 0, reputation_level: user.role === "GUIDE" ? "Local Guide" : "Contributor" } as PublicProfile);
  return <SafeAreaView style={styles.safe} edges={["top"]}><FlatList data={items} keyExtractor={(item, index) => item.id || String(index)} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}
    ListHeaderComponent={<><ScreenHeader title="Profile" back={false} right={<IconButton icon="menu-outline" label="Profile menu" onPress={() => setMenu(true)} />} /><View style={styles.identity}><Avatar uri={visible.avatar_url} name={visible.display_name || user.email} size={92} /><View style={styles.identityCopy}><View style={styles.nameRow}><Text style={styles.name} numberOfLines={1}>{visible.display_name || "City explorer"}</Text>{visible.identity_verified && <Ionicons name="checkmark-circle" size={18} color={colors.free} />}</View><Text style={styles.location}>{visible.neighborhood || visible.city || "Bratislava"}</Text><Text style={styles.reputation}>{visible.role === "GUIDE" ? "Local Guide · " : ""}{visible.reputation_level}</Text></View></View>{visible.bio ? <Text style={styles.bio}>{visible.bio}</Text> : null}<View style={styles.stats}><Stat value={visible.contributions_count ?? 0} label="Contributions" onPress={() => setTab("contributions")} /><Stat value={visible.followers} label="Followers" onPress={() => router.push({ pathname: "/social/followers", params: { userId: user.id } })} /><Stat value={visible.following} label="Following" onPress={() => router.push({ pathname: "/social/following", params: { userId: user.id } })} /></View><Pressable onPress={() => router.push("/account")} style={({ pressed }) => [styles.edit, pressed && styles.pressed]}><Text style={styles.editText}>Edit profile</Text></Pressable><View style={styles.tabs}>{(["contributions", "reviews", "collections"] as Tab[]).map(value => <Chip key={value} title={value[0].toUpperCase() + value.slice(1)} active={tab === value} onPress={() => setTab(value)} />)}</View>{error ? <Text style={styles.error}>{error}</Text> : null}{loading && !items.length ? <SkeletonList rows={3} /> : null}</>}
    ListEmptyComponent={!loading ? <EmptyState title={`No ${tab} yet`} subtitle={tab === "collections" ? "Create a collection from your saved places and events." : `Your public ${tab} will appear here.`} action={tab === "collections" ? "Create collection" : undefined} onAction={tab === "collections" ? () => router.push("/collection") : undefined} /> : null}
    renderItem={({ item }) => <ListItem icon={tab === "contributions" ? item.kind === "event" ? "calendar-outline" : "location-outline" : tab === "reviews" ? "star-outline" : "albums-outline"} title={item.title || item.target_name || item.kind || "Collection"} subtitle={tab === "reviews" ? item.body : tab === "collections" ? `${item.items?.length || 0} items · ${item.public ? "Public" : "Private"}` : new Date(item.created_at).toLocaleDateString()} onPress={item.published_id ? () => item.kind === "event" ? router.push(`/event/${item.published_id}`) : item.kind === "place" ? router.push(`/place/${item.published_id}`) : router.push(`/utility/${item.published_id}`) : undefined} />}
    ListFooterComponent={more ? <Text style={styles.more} onPress={() => load(true)}>{loading ? "Loading…" : "Load more"}</Text> : null}
  />
  <OverflowMenu visible={menu} title="Profile menu" onClose={() => setMenu(false)}>
    <ListItem icon="bookmark-outline" title="Saved" subtitle="Your personal event library" onPress={() => { setMenu(false); router.push("/(tabs)/saved"); }} />
    <ListItem icon="pulse-outline" title="Your activity" subtitle="Contributions, decisions and appeals" onPress={() => { setMenu(false); router.push("/activity"); }} />
    <ListItem icon="albums-outline" title="Collections" onPress={() => { setMenu(false); router.push("/collections"); }} />
    <ListItem icon="people-outline" title="Following" subtitle="People, places and local interests" onPress={() => { setMenu(false); router.push("/following"); }} />
    {["ORGANIZER", "ADMIN"].includes(user.role) && <ListItem icon="business-outline" title="Organizer tools" onPress={() => { setMenu(false); router.push("/organizer"); }} />}
    {["GUIDE", "ADMIN"].includes(user.role) && <ListItem icon="navigate-outline" title="Local Guide tools" subtitle="Your public contribution history" onPress={() => { setMenu(false); router.push("/activity"); }} />}
    {["MODERATOR", "ADMIN"].includes(user.role) && <ListItem icon="shield-checkmark-outline" title="Moderator tools" onPress={() => { setMenu(false); router.push("/moderator"); }} />}
    <ListItem icon="settings-outline" title="Settings & privacy" onPress={() => { setMenu(false); router.push("/account"); }} />
    <ListItem icon="ban-outline" title="Blocked users" onPress={() => { setMenu(false); router.push("/blocked"); }} />
    <ListItem icon="log-out-outline" title="Log out" onPress={signOut} />
  </OverflowMenu></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background }, content: { paddingHorizontal: 18, paddingBottom: 92, flexGrow: 1 }, guest: { flex: 1, justifyContent: "center", padding: 28 }, guestTitle: { color: colors.text, fontFamily: fonts.black, fontSize: 30, marginTop: 18 }, guestText: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 14, lineHeight: 21, marginVertical: 12 }, primary: { minHeight: 52, borderRadius: 17, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center", marginTop: 12 }, primaryText: { color: colors.white, fontFamily: fonts.semibold }, secondary: { minHeight: 52, alignItems: "center", justifyContent: "center" }, secondaryText: { color: colors.text, fontFamily: fonts.semibold },
  identity: { flexDirection: "row", alignItems: "center", gap: 17, marginTop: 12 }, identityCopy: { flex: 1, minWidth: 0 }, nameRow: { flexDirection: "row", alignItems: "center", gap: 6 }, name: { flexShrink: 1, color: colors.text, fontFamily: fonts.black, fontSize: 24, letterSpacing: -.6 }, location: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12, marginTop: 5 }, reputation: { color: colors.primaryDark, fontFamily: fonts.semibold, fontSize: 10, marginTop: 4 }, bio: { color: colors.text, fontFamily: fonts.regular, fontSize: 13, lineHeight: 20, marginTop: 15 },
  stats: { flexDirection: "row", marginTop: 16, borderTopWidth: StyleSheet.hairlineWidth, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.border }, edit: { minHeight: 44, borderRadius: 15, backgroundColor: colors.text, alignItems: "center", justifyContent: "center", marginTop: 14 }, editText: { color: colors.white, fontFamily: fonts.semibold, fontSize: 12 }, pressed: { opacity: .78 }, tabs: { flexDirection: "row", gap: 7, marginTop: 20, marginBottom: 6 }, error: { color: colors.danger, marginVertical: 10 }, more: { color: colors.primaryDark, textAlign: "center", padding: 18 },
});
