"""Community trust and account lifecycle. Frozen PostgreSQL schema snapshot."""
from alembic import op
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None

def upgrade():
    op.execute("ALTER TABLE users ADD COLUMN role VARCHAR NOT NULL DEFAULT 'USER'")
    op.execute('ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT false')
    op.execute('ALTER TABLE users ADD COLUMN identity_verified BOOLEAN NOT NULL DEFAULT false')
    op.execute('ALTER TABLE users ADD COLUMN reputation INTEGER NOT NULL DEFAULT 0')
    op.execute('ALTER TABLE users ADD COLUMN token_version INTEGER NOT NULL DEFAULT 0')
    op.execute('ALTER TABLE users ADD COLUMN active BOOLEAN NOT NULL DEFAULT true')
    op.execute('ALTER TABLE users ADD COLUMN avatar_url VARCHAR')
    op.execute('ALTER TABLE users ADD COLUMN bio TEXT')
    op.execute("ALTER TABLE users ADD COLUMN city VARCHAR NOT NULL DEFAULT 'Bratislava'")
    op.execute('ALTER TABLE users ADD COLUMN neighborhood VARCHAR')
    op.execute('ALTER TABLE users ADD COLUMN public_profile BOOLEAN NOT NULL DEFAULT true')
    op.execute('ALTER TABLE users ADD COLUMN allow_general_messages BOOLEAN NOT NULL DEFAULT false')
    op.execute('\nCREATE TABLE billing_receipts (\n\tid VARCHAR NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n')
    op.execute('\nCREATE TABLE mail_outbox (\n\trecipient VARCHAR NOT NULL, \n\tsubject VARCHAR NOT NULL, \n\tbody TEXT NOT NULL, \n\tattempts INTEGER NOT NULL, \n\tnext_attempt_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tsent_at TIMESTAMP WITHOUT TIME ZONE, \n\terror TEXT, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n')
    op.execute('\nCREATE TABLE rate_buckets (\n\tkey VARCHAR NOT NULL, \n\t"window" INTEGER NOT NULL, \n\tcount INTEGER NOT NULL, \n\tPRIMARY KEY (key, "window")\n)\n\n')
    op.execute('\nCREATE TABLE action_tokens (\n\tuser_id UUID NOT NULL, \n\ttoken_hash VARCHAR NOT NULL, \n\tpurpose VARCHAR NOT NULL, \n\texpires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tused_at TIMESTAMP WITHOUT TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tUNIQUE (token_hash)\n)\n\n')
    op.execute('CREATE INDEX ix_action_tokens_user_id ON action_tokens (user_id)')
    op.execute('\nCREATE TABLE audit_logs (\n\tactor_id UUID, \n\taction VARCHAR NOT NULL, \n\ttarget_type VARCHAR NOT NULL, \n\ttarget_id VARCHAR NOT NULL, \n\tdetails JSON NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(actor_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_audit_logs_action ON audit_logs (action)')
    op.execute('CREATE INDEX ix_audit_logs_target_id ON audit_logs (target_id)')
    op.execute('\nCREATE TABLE city_utilities (\n\tkind VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\tlatitude FLOAT NOT NULL, \n\tlongitude FLOAT NOT NULL, \n\taddress VARCHAR, \n\topening_hours VARCHAR, \n\tfree BOOLEAN, \n\tfee FLOAT, \n\twheelchair_accessible BOOLEAN, \n\tchanging_table BOOLEAN, \n\tcleanliness INTEGER, \n\toperational_status VARCHAR NOT NULL, \n\tlast_confirmed_at TIMESTAMP WITHOUT TIME ZONE, \n\tcontributor_id UUID, \n\tsource_url VARCHAR, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(contributor_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_city_utilities_kind ON city_utilities (kind)')
    op.execute('CREATE INDEX ix_city_utilities_last_confirmed_at ON city_utilities (last_confirmed_at)')
    op.execute('CREATE INDEX ix_city_utilities_latitude ON city_utilities (latitude)')
    op.execute('CREATE INDEX ix_city_utilities_longitude ON city_utilities (longitude)')
    op.execute('\nCREATE TABLE collections (\n\tuser_id UUID NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tdescription TEXT, \n\tneighborhood VARCHAR, \n\titems JSON NOT NULL, \n\tpublic BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n')
    op.execute('\nCREATE TABLE follows (\n\tuser_id UUID NOT NULL, \n\ttarget_type VARCHAR NOT NULL, \n\ttarget_id VARCHAR NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_follow UNIQUE (user_id, target_type, target_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_follows_target_id ON follows (target_id)')
    op.execute('CREATE INDEX ix_follows_user_id ON follows (user_id)')
    op.execute('\nCREATE TABLE messages (\n\tsender_id UUID NOT NULL, \n\trecipient_id UUID NOT NULL, \n\tbody TEXT NOT NULL, \n\tread_at TIMESTAMP WITHOUT TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(sender_id) REFERENCES users (id), \n\tFOREIGN KEY(recipient_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_messages_recipient_id ON messages (recipient_id)')
    op.execute('CREATE INDEX ix_messages_sender_id ON messages (sender_id)')
    op.execute('\nCREATE TABLE notifications (\n\tuser_id UUID NOT NULL, \n\tkind VARCHAR NOT NULL, \n\tbody TEXT NOT NULL, \n\ttarget_id VARCHAR, \n\tread_at TIMESTAMP WITHOUT TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_notifications_user_id ON notifications (user_id)')
    op.execute('\nCREATE TABLE places (\n\tname VARCHAR NOT NULL, \n\tdescription TEXT, \n\tcategory VARCHAR NOT NULL, \n\taddress VARCHAR NOT NULL, \n\tlatitude FLOAT NOT NULL, \n\tlongitude FLOAT NOT NULL, \n\tneighborhood VARCHAR, \n\twebsite VARCHAR, \n\taccessibility JSON NOT NULL, \n\toperational_status VARCHAR NOT NULL, \n\tlast_confirmed_at TIMESTAMP WITHOUT TIME ZONE, \n\ttrust_level VARCHAR NOT NULL, \n\tcontributor_id UUID, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(contributor_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_places_latitude ON places (latitude)')
    op.execute('CREATE INDEX ix_places_longitude ON places (longitude)')
    op.execute('CREATE INDEX ix_places_name ON places (name)')
    op.execute('\nCREATE TABLE reports (\n\tuser_id UUID NOT NULL, \n\ttarget_type VARCHAR NOT NULL, \n\ttarget_id VARCHAR NOT NULL, \n\treason TEXT NOT NULL, \n\tstate VARCHAR NOT NULL, \n\tdecision TEXT, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_reports_state ON reports (state)')
    op.execute('CREATE INDEX ix_reports_target_id ON reports (target_id)')
    op.execute('\nCREATE TABLE reviews (\n\tuser_id UUID NOT NULL, \n\ttarget_type VARCHAR NOT NULL, \n\ttarget_id VARCHAR NOT NULL, \n\tbody TEXT NOT NULL, \n\tdimensions JSON NOT NULL, \n\tstate VARCHAR NOT NULL, \n\tattendance_verified BOOLEAN NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_review UNIQUE (user_id, target_type, target_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_reviews_target_id ON reviews (target_id)')
    op.execute('CREATE INDEX ix_reviews_user_id ON reviews (user_id)')
    op.execute('\nCREATE TABLE submissions (\n\tuser_id UUID NOT NULL, \n\tkind VARCHAR NOT NULL, \n\tpayload JSON NOT NULL, \n\tstate VARCHAR NOT NULL, \n\trisk_flags JSON NOT NULL, \n\tpublished_id VARCHAR, \n\tdecision_reason TEXT, \n\treviewer_id UUID, \n\tappeal TEXT, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(reviewer_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_submissions_kind ON submissions (kind)')
    op.execute('CREATE INDEX ix_submissions_state ON submissions (state)')
    op.execute('CREATE INDEX ix_submissions_user_id ON submissions (user_id)')
    op.execute('\nCREATE TABLE user_blocks (\n\tuser_id UUID NOT NULL, \n\tblocked_id UUID NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_block UNIQUE (user_id, blocked_id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(blocked_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_user_blocks_blocked_id ON user_blocks (blocked_id)')
    op.execute('CREATE INDEX ix_user_blocks_user_id ON user_blocks (user_id)')
    op.execute('\nCREATE TABLE helpful_votes (\n\treview_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_helpful UNIQUE (review_id, user_id), \n\tFOREIGN KEY(review_id) REFERENCES reviews (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_helpful_votes_review_id ON helpful_votes (review_id)')
    op.execute('\nCREATE TABLE organizations (\n\tname VARCHAR NOT NULL, \n\tdescription TEXT, \n\twebsite VARCHAR, \n\tvenue_id UUID, \n\tverified BOOLEAN NOT NULL, \n\ttier VARCHAR NOT NULL, \n\tstripe_customer_id VARCHAR, \n\tstripe_subscription_id VARCHAR, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(venue_id) REFERENCES venues (id), \n\tUNIQUE (stripe_customer_id), \n\tUNIQUE (stripe_subscription_id)\n)\n\n')
    op.execute('CREATE INDEX ix_organizations_name ON organizations (name)')
    op.execute('\nCREATE TABLE review_revisions (\n\treview_id UUID NOT NULL, \n\tbody TEXT NOT NULL, \n\tdimensions JSON NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(review_id) REFERENCES reviews (id)\n)\n\n')
    op.execute('CREATE INDEX ix_review_revisions_review_id ON review_revisions (review_id)')
    op.execute('\nCREATE TABLE utility_confirmations (\n\tutility_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\toperational_status VARCHAR NOT NULL, \n\tcleanliness INTEGER, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(utility_id) REFERENCES city_utilities (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_utility_confirmations_utility_id ON utility_confirmations (utility_id)')
    op.execute('\nCREATE TABLE organization_members (\n\torganization_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\trole VARCHAR NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_organization_member UNIQUE (organization_id, user_id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_organization_members_organization_id ON organization_members (organization_id)')
    op.execute('CREATE INDEX ix_organization_members_user_id ON organization_members (user_id)')
    op.execute('\nCREATE TABLE comments (\n\tevent_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tbody TEXT NOT NULL, \n\tstate VARCHAR NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(event_id) REFERENCES events (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id)\n)\n\n')
    op.execute('CREATE INDEX ix_comments_event_id ON comments (event_id)')
    op.execute('\nCREATE TABLE promotions (\n\torganization_id UUID NOT NULL, \n\tevent_id UUID NOT NULL, \n\tstarts_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tends_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tlabel VARCHAR NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(organization_id) REFERENCES organizations (id), \n\tFOREIGN KEY(event_id) REFERENCES events (id)\n)\n\n')
    op.execute('ALTER TABLE events ADD COLUMN contributor_id UUID REFERENCES users(id)')
    op.execute('ALTER TABLE events ADD COLUMN organization_id UUID REFERENCES organizations(id)')
    op.execute("ALTER TABLE events ADD COLUMN trust_level VARCHAR NOT NULL DEFAULT 'Unverified'")
    op.execute('ALTER TABLE events ADD COLUMN ticket_url VARCHAR')
    op.execute('ALTER TABLE events ADD COLUMN neighborhood VARCHAR')
    op.execute('CREATE INDEX ix_events_contributor_id ON events(contributor_id)')
    op.execute('CREATE INDEX ix_events_organization_id ON events(organization_id)')

def downgrade():
    op.drop_column("events", 'organization_id')
    op.drop_column("events", 'contributor_id')
    op.drop_column("events", 'trust_level')
    op.drop_column("events", 'ticket_url')
    op.drop_column("events", 'neighborhood')
    op.drop_table('promotions')
    op.drop_table('comments')
    op.drop_table('organization_members')
    op.drop_table('utility_confirmations')
    op.drop_table('review_revisions')
    op.drop_table('organizations')
    op.drop_table('helpful_votes')
    op.drop_table('user_blocks')
    op.drop_table('submissions')
    op.drop_table('reviews')
    op.drop_table('reports')
    op.drop_table('places')
    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('follows')
    op.drop_table('collections')
    op.drop_table('city_utilities')
    op.drop_table('audit_logs')
    op.drop_table('action_tokens')
    op.drop_table('rate_buckets')
    op.drop_table('mail_outbox')
    op.drop_table('billing_receipts')
    op.drop_column("users", 'allow_general_messages')
    op.drop_column("users", 'public_profile')
    op.drop_column("users", 'neighborhood')
    op.drop_column("users", 'city')
    op.drop_column("users", 'bio')
    op.drop_column("users", 'avatar_url')
    op.drop_column("users", 'active')
    op.drop_column("users", 'token_version')
    op.drop_column("users", 'reputation')
    op.drop_column("users", 'identity_verified')
    op.drop_column("users", 'email_verified')
    op.drop_column("users", 'role')
